"""initial schema

Revision ID: bde2616e09ed
Revises: 
Create Date: 2026-08-21 19:25:40.753028
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'bde2616e09ed'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('broadcasters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('competition', sa.String(length=32), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('url', sa.String(length=256), nullable=False),
    sa.Column('verified_on', sa.String(length=10), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('country', 'competition', name='uq_broadcaster_country_comp')
    )
    with op.batch_alter_table('broadcasters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_broadcasters_country'), ['country'], unique=False)

    op.create_table('cron_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cron_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cron_runs_job'), ['job'], unique=False)

    op.create_table('odds_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fixture_id', sa.Integer(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('home', sa.Float(), nullable=False),
    sa.Column('draw', sa.Float(), nullable=False),
    sa.Column('away', sa.Float(), nullable=False),
    sa.Column('bookmaker', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('odds_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_odds_history_fixture_id'), ['fixture_id'], unique=False)
        batch_op.create_index('ix_odds_history_fixture_time', ['fixture_id', 'captured_at'], unique=False)

    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=16), nullable=False),
    sa.Column('display_name', sa.String(length=32), nullable=False),
    sa.Column('city', sa.String(length=64), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('code_hash', sa.String(length=128), nullable=False),
    sa.Column('fpl_entry_id', sa.Integer(), nullable=True),
    sa.Column('push_subscription', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_people_key'), ['key'], unique=True)

    op.create_table('polls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('opens_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closes_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('table_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gameweek', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('table_snapshots', schema=None) as batch_op:
        batch_op.create_index('ix_table_snapshots_captured', ['captured_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_table_snapshots_captured_at'), ['captured_at'], unique=False)

    op.create_table('upstream_calls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('endpoint', sa.String(length=128), nullable=False),
    sa.Column('called_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('quota_remaining', sa.String(length=32), nullable=False),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('upstream_calls', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_upstream_calls_source'), ['source'], unique=False)
        batch_op.create_index('ix_upstream_calls_source_time', ['source', 'called_at'], unique=False)

    op.create_table('bets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proposer_id', sa.Integer(), nullable=False),
    sa.Column('opponent_id', sa.Integer(), nullable=False),
    sa.Column('terms', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('winner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['opponent_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['proposer_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['winner_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fpl_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gameweek', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fpl_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fpl_snapshots_entry_id'), ['entry_id'], unique=False)
        batch_op.create_index('ix_fpl_snapshots_gw_person', ['gameweek', 'person_id'], unique=False)

    op.create_table('leaderboard_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gameweek', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('table_pts', sa.Integer(), nullable=False),
    sa.Column('award_pts', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('leaderboard_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_leaderboard_runs_computed_at'), ['computed_at'], unique=False)
        batch_op.create_index('ix_leaderboard_runs_gw_person', ['gameweek', 'person_id'], unique=False)

    op.create_table('moments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('r2_key', sa.String(length=256), nullable=False),
    sa.Column('caption', sa.Text(), nullable=False),
    sa.Column('content_type', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('moments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_moments_created_at'), ['created_at'], unique=False)

    op.create_table('poll_votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('poll_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('choice', sa.String(length=128), nullable=False),
    sa.Column('voted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['poll_id'], ['polls.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('poll_id', 'person_id', name='uq_vote_poll_person')
    )
    with op.batch_alter_table('poll_votes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_poll_votes_poll_id'), ['poll_id'], unique=False)

    op.create_table('predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked', sa.Boolean(), nullable=False),
    sa.Column('is_draft', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('person_id', 'kind', name='uq_prediction_person_kind')
    )
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_predictions_person_id'), ['person_id'], unique=False)

    op.create_table('quotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('subject_type', sa.String(length=16), nullable=True),
    sa.Column('subject_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quotes_created_at'), ['created_at'], unique=False)

    op.create_table('watch_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('fixture_id', sa.Integer(), nullable=False),
    sa.Column('watched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gameweek', sa.Integer(), nullable=False),
    sa.Column('local_hour', sa.Integer(), nullable=False),
    sa.Column('night_medal', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('person_id', 'fixture_id', name='uq_watch_person_fixture')
    )
    with op.batch_alter_table('watch_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_watch_log_fixture_id'), ['fixture_id'], unique=False)
        batch_op.create_index('ix_watch_log_person_fixture', ['person_id', 'fixture_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_watch_log_person_id'), ['person_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watch_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_watch_log_person_id'))
        batch_op.drop_index('ix_watch_log_person_fixture')
        batch_op.drop_index(batch_op.f('ix_watch_log_fixture_id'))

    op.drop_table('watch_log')
    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quotes_created_at'))

    op.drop_table('quotes')
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_predictions_person_id'))

    op.drop_table('predictions')
    with op.batch_alter_table('poll_votes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_poll_votes_poll_id'))

    op.drop_table('poll_votes')
    with op.batch_alter_table('moments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_moments_created_at'))

    op.drop_table('moments')
    with op.batch_alter_table('leaderboard_runs', schema=None) as batch_op:
        batch_op.drop_index('ix_leaderboard_runs_gw_person')
        batch_op.drop_index(batch_op.f('ix_leaderboard_runs_computed_at'))

    op.drop_table('leaderboard_runs')
    with op.batch_alter_table('fpl_snapshots', schema=None) as batch_op:
        batch_op.drop_index('ix_fpl_snapshots_gw_person')
        batch_op.drop_index(batch_op.f('ix_fpl_snapshots_entry_id'))

    op.drop_table('fpl_snapshots')
    op.drop_table('bets')
    with op.batch_alter_table('upstream_calls', schema=None) as batch_op:
        batch_op.drop_index('ix_upstream_calls_source_time')
        batch_op.drop_index(batch_op.f('ix_upstream_calls_source'))

    op.drop_table('upstream_calls')
    with op.batch_alter_table('table_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_table_snapshots_captured_at'))
        batch_op.drop_index('ix_table_snapshots_captured')

    op.drop_table('table_snapshots')
    op.drop_table('polls')
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_people_key'))

    op.drop_table('people')
    with op.batch_alter_table('odds_history', schema=None) as batch_op:
        batch_op.drop_index('ix_odds_history_fixture_time')
        batch_op.drop_index(batch_op.f('ix_odds_history_fixture_id'))

    op.drop_table('odds_history')
    with op.batch_alter_table('cron_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cron_runs_job'))

    op.drop_table('cron_runs')
    with op.batch_alter_table('broadcasters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_broadcasters_country'))

    op.drop_table('broadcasters')
    # ### end Alembic commands ###
