/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign In
         * @description One field, one code word, compared constant-time.
         */
        post: operations["sign_in_api_session_post"];
        /** Sign Out */
        delete: operations["sign_out_api_session_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clubs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Clubs
         * @description The canonical club table, so the frontend never guesses a crest colour.
         */
        get: operations["clubs_api_clubs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/table": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Table */
        get: operations["table_api_table_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fixtures": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fixtures */
        get: operations["fixtures_api_fixtures_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fixtures/{fixture_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fixture */
        get: operations["fixture_api_fixtures__fixture_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/season": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Season */
        get: operations["season_api_season_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/home": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Home
         * @description Everything the front page needs, in one request.
         */
        get: operations["home_api_home_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/table/projected": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Projected
         * @description Current points plus every remaining fixture resolved to last season.
         */
        get: operations["projected_api_table_projected_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/predictions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Predictions */
        get: operations["list_predictions_api_predictions_get"];
        /**
         * Put Prediction
         * @description Owner only, and only before the lock.
         */
        put: operations["put_prediction_api_predictions_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/predictions/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Preview
         * @description Score a draft table against a finished season.
         *
         *     The picker calls this rather than reimplementing the rules in TypeScript --
         *     two implementations of the scoring rules is a bug waiting to happen.
         */
        post: operations["preview_api_predictions_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fpl/standings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Standings */
        get: operations["standings_api_fpl_standings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream
         * @description Subscribe to live score, FPL and odds changes for as long as the tab is open.
         */
        get: operations["stream_api_stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Status */
        get: operations["status_api_admin_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/broadcasters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listings */
        get: operations["listings_api_admin_broadcasters_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Healthz
         * @description Liveness: the process is up. Never touches a dependency.
         */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readyz
         * @description Readiness: the cache answers and the fixture list has been filled.
         */
        get: operations["readyz_readyz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AdminStatusOut */
        AdminStatusOut: {
            /** Caches */
            caches: components["schemas"]["CacheAge"][];
            /** Quotas */
            quotas: components["schemas"]["QuotaOut"][];
            /** Cron */
            cron: components["schemas"]["CronRunOut"][];
            /** Missing Keys */
            missing_keys: string[];
            /** Environment */
            environment: string;
        };
        /** AwardPicks */
        "AwardPicks-Input": {
            /**
             * Golden Boot
             * @default
             */
            golden_boot: string;
            /**
             * Golden Glove
             * @default
             */
            golden_glove: string;
            /**
             * Defender
             * @default
             */
            defender: string;
            /**
             * Playmaker
             * @default
             */
            playmaker: string;
            /**
             * Player Of The Season
             * @default
             */
            player_of_the_season: string;
        };
        /** AwardPicks */
        "AwardPicks-Output": {
            /**
             * Golden Boot
             * @default
             */
            golden_boot: string;
            /**
             * Golden Glove
             * @default
             */
            golden_glove: string;
            /**
             * Defender
             * @default
             */
            defender: string;
            /**
             * Playmaker
             * @default
             */
            playmaker: string;
            /**
             * Player Of The Season
             * @default
             */
            player_of_the_season: string;
        };
        /** BroadcasterOut */
        BroadcasterOut: {
            /** Country */
            country: string;
            /** Competition */
            competition: string;
            /** Provider */
            provider: string;
            /**
             * Url
             * @default
             */
            url: string;
            /**
             * Verified On
             * @default
             */
            verified_on: string;
            /**
             * Note
             * @default
             */
            note: string;
        };
        /** CacheAge */
        CacheAge: {
            /** Name */
            name: string;
            /** Source */
            source: string;
            /** Age Seconds */
            age_seconds: number;
            /** Stale */
            stale: boolean;
        };
        /** ChampionsLeaguePicks */
        "ChampionsLeaguePicks-Input": {
            /**
             * Winner
             * @default
             */
            winner: string;
            /**
             * Finalist A
             * @default
             */
            finalist_a: string;
            /**
             * Finalist B
             * @default
             */
            finalist_b: string;
            /**
             * Top Scorer
             * @default
             */
            top_scorer: string;
            /**
             * Draft
             * @default false
             */
            draft: boolean;
        };
        /** ChampionsLeaguePicks */
        "ChampionsLeaguePicks-Output": {
            /**
             * Winner
             * @default
             */
            winner: string;
            /**
             * Finalist A
             * @default
             */
            finalist_a: string;
            /**
             * Finalist B
             * @default
             */
            finalist_b: string;
            /**
             * Top Scorer
             * @default
             */
            top_scorer: string;
            /**
             * Draft
             * @default false
             */
            draft: boolean;
        };
        /**
         * ClubOut
         * @description A club, with everything a crest needs and nothing it does not.
         */
        ClubOut: {
            /** Short Name */
            short_name: string;
            /** Name */
            name: string;
            /** Full Name */
            full_name: string;
            /** Primary */
            primary: string;
            /** On Primary */
            on_primary: string;
            /** Fpl Id */
            fpl_id: number;
        };
        /**
         * CronRunOut
         * @description One scheduler run, as shown in the admin cron log.
         */
        CronRunOut: {
            /** Job */
            job: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Finished At */
            finished_at: string | null;
            /**
             * Ok
             * @default true
             */
            ok: boolean;
            /**
             * Detail
             * @default
             */
            detail: string;
        };
        /** ErrorOut */
        ErrorOut: {
            /** Detail */
            detail: string;
        };
        /** FixtureListOut */
        FixtureListOut: {
            /** Fixtures */
            fixtures: components["schemas"]["FixtureOut"][];
            freshness: components["schemas"]["Freshness"];
            /** Empty Message */
            empty_message: string | null;
        };
        /** FixtureOut */
        FixtureOut: {
            /** Id */
            id: number;
            /** Gameweek */
            gameweek: number;
            /** Kickoff */
            kickoff: string | null;
            home: components["schemas"]["ClubOut"];
            away: components["schemas"]["ClubOut"];
            /** Home Score */
            home_score: number | null;
            /** Away Score */
            away_score: number | null;
            /**
             * Started
             * @default false
             */
            started: boolean;
            /**
             * Finished
             * @default false
             */
            finished: boolean;
            /**
             * Postponed
             * @default false
             */
            postponed: boolean;
            /**
             * Minutes
             * @default 0
             */
            minutes: number;
            /** Local Times */
            local_times: components["schemas"]["LocalTimeOut"][];
            odds: components["schemas"]["OddsPrice"] | null;
            /** Derby */
            derby: string | null;
            /** Watched By */
            watched_by: string[];
            /**
             * Watch Open
             * @default false
             */
            watch_open: boolean;
        };
        /** FplStandingRow */
        FplStandingRow: {
            /** Entry Id */
            entry_id: number;
            /** Entry Name */
            entry_name: string;
            /** Player Name */
            player_name: string;
            /** Person */
            person: string | null;
            /** Rank */
            rank: number | null;
            /**
             * Total
             * @default 0
             */
            total: number;
            /**
             * Event Total
             * @default 0
             */
            event_total: number;
            /**
             * Pending
             * @default false
             */
            pending: boolean;
        };
        /** FplStandingsOut */
        FplStandingsOut: {
            /** League Id */
            league_id: number;
            /** League Name */
            league_name: string;
            /** Rows */
            rows: components["schemas"]["FplStandingRow"][];
            /** Gameweek */
            gameweek: number;
            freshness: components["schemas"]["Freshness"];
            /** Empty Message */
            empty_message: string | null;
            /** Unmapped */
            unmapped: number[];
        };
        /**
         * Freshness
         * @description How old a cached payload is, so a panel can say so rather than lie.
         */
        Freshness: {
            /** Source */
            source: string;
            /** Age Seconds */
            age_seconds: number;
            /** Stale */
            stale: boolean;
            /**
             * Available
             * @default true
             */
            available: boolean;
            /** Reason */
            reason: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HomeOut */
        HomeOut: {
            next_match: components["schemas"]["NextMatchOut"];
            season: components["schemas"]["SeasonOut"];
            /** Line Of The Day */
            line_of_the_day: string | null;
        };
        /**
         * LocalTimeOut
         * @description One kickoff rendered for one city.
         */
        LocalTimeOut: {
            /** Place */
            place: string;
            /** Person */
            person: string;
            /** City */
            city: string;
            /** Timezone */
            timezone: string;
            /**
             * Iso
             * Format: date-time
             */
            iso: string;
            /** Time */
            time: string;
            /** Weekday */
            weekday: string;
            /** Day */
            day: string;
            /** Offset */
            offset: string;
            /** Abbreviation */
            abbreviation: string;
            /** Is Night */
            is_night: boolean;
            /** Day Shift */
            day_shift: number;
            /** Broadcaster */
            broadcaster: string | null;
            /** Broadcaster Url */
            broadcaster_url: string | null;
            /** Verified On */
            verified_on: string | null;
        };
        /** LoginIn */
        LoginIn: {
            /** Code */
            code: string;
        };
        /** MeOut */
        MeOut: {
            person: components["schemas"]["PersonOut"];
            /** People */
            people: components["schemas"]["PersonOut"][];
            /** Season */
            season: string;
            /**
             * Prediction Lock
             * Format: date-time
             */
            prediction_lock: string;
            /** Locked */
            locked: boolean;
            /**
             * Server Time
             * Format: date-time
             */
            server_time: string;
        };
        /** NextMatchOut */
        NextMatchOut: {
            fixture: components["schemas"]["FixtureOut"] | null;
            /** Countdown Seconds */
            countdown_seconds: number | null;
            /**
             * In Play
             * @default false
             */
            in_play: boolean;
            /** Message */
            message: string | null;
        };
        /** OddsPrice */
        OddsPrice: {
            /** Home */
            home: number | null;
            /** Draw */
            draw: number | null;
            /** Away */
            away: number | null;
            /**
             * Bookmaker
             * @default bet365
             */
            bookmaker: string;
            /** Captured At */
            captured_at: string | null;
            /** Drift */
            drift: {
                [key: string]: number;
            } | null;
            /**
             * Available
             * @default true
             */
            available: boolean;
            /** Reason */
            reason: string | null;
        };
        /** PersonOut */
        PersonOut: {
            /** Key */
            key: string;
            /** Name */
            name: string;
            /** City */
            city: string;
            /** Timezone */
            timezone: string;
            /** Country */
            country: string;
            /** Fpl Entry Id */
            fpl_entry_id: number | null;
        };
        /** PredictionIn */
        PredictionIn: {
            /** Table */
            table?: string[];
            awards?: components["schemas"]["AwardPicks-Input"];
            champions_league?: components["schemas"]["ChampionsLeaguePicks-Input"];
        };
        /** PredictionOut */
        PredictionOut: {
            /** Person */
            person: string;
            /** Filed */
            filed: boolean;
            /**
             * Redacted
             * @default false
             */
            redacted: boolean;
            /** Table */
            table: string[];
            awards: components["schemas"]["AwardPicks-Output"] | null;
            champions_league: components["schemas"]["ChampionsLeaguePicks-Output"] | null;
            /** Submitted At */
            submitted_at: string | null;
            /**
             * Locked
             * @default false
             */
            locked: boolean;
            /**
             * Status
             * @default open
             * @enum {string}
             */
            status: "filed" | "open" | "did-not-file";
        };
        /** PredictionsOut */
        PredictionsOut: {
            /** Predictions */
            predictions: components["schemas"]["PredictionOut"][];
            /** Locked */
            locked: boolean;
            /**
             * Lock At
             * Format: date-time
             */
            lock_at: string;
            /** Seconds Remaining */
            seconds_remaining: number;
        };
        /** PreviewIn */
        PreviewIn: {
            /** Table */
            table: string[];
            awards?: components["schemas"]["AwardPicks-Input"] | null;
            /**
             * Against Season
             * @default 2025-26
             */
            against_season: string;
        };
        /** PreviewOut */
        PreviewOut: {
            /** Total */
            total: number;
            /** Table Points */
            table_points: number;
            /** Award Points */
            award_points: number;
            /** Exact Hits */
            exact_hits: number;
            /** Near Hits */
            near_hits: number;
            /** Top Four Bonus */
            top_four_bonus: number;
            /** Champion Bonus */
            champion_bonus: number;
            /** Against Season */
            against_season: string;
            /** Per Club */
            per_club: {
                [key: string]: unknown;
            }[];
        };
        /** ProjectedTableOut */
        ProjectedTableOut: {
            /** Rows */
            rows: components["schemas"]["TableRowOut"][];
            /** Gameweek */
            gameweek: number;
            /** Matches Played */
            matches_played: number;
            /** Season Started */
            season_started: boolean;
            freshness: components["schemas"]["Freshness"];
            /** Empty Message */
            empty_message: string | null;
            /** Modelled Rows */
            modelled_rows: string[];
            /**
             * Method
             * @default
             */
            method: string;
        };
        /** QuotaOut */
        QuotaOut: {
            /** Source */
            source: string;
            /** Used */
            used: number;
            /** Budget */
            budget: number;
            /** Remaining */
            remaining: number;
            /** Window */
            window: string;
            /**
             * Note
             * @default
             */
            note: string;
        };
        /**
         * SeasonOut
         * @description Computed from fixture data and the current date, never hardcoded.
         */
        SeasonOut: {
            /**
             * Starts
             * Format: date-time
             */
            starts: string;
            /**
             * Ends
             * Format: date-time
             */
            ends: string;
            /**
             * Today
             * Format: date-time
             */
            today: string;
            /** Percent */
            percent: number;
            /** Day */
            day: number;
            /** Total Days */
            total_days: number;
            /** Days Remaining */
            days_remaining: number;
            /** Gameweeks Played */
            gameweeks_played: number;
            /** Gameweeks Total */
            gameweeks_total: number;
            /** Matches Played */
            matches_played: number;
            /** Matches Total */
            matches_total: number;
            /** Matches Remaining */
            matches_remaining: number;
            /** Watched */
            watched: number;
            /** Markers */
            markers: components["schemas"]["TimelineMarker"][];
        };
        /** TableOut */
        TableOut: {
            /** Rows */
            rows: components["schemas"]["TableRowOut"][];
            /** Gameweek */
            gameweek: number;
            /** Matches Played */
            matches_played: number;
            /** Season Started */
            season_started: boolean;
            freshness: components["schemas"]["Freshness"];
            /** Empty Message */
            empty_message: string | null;
        };
        /** TableRowOut */
        TableRowOut: {
            /** Position */
            position: number;
            club: components["schemas"]["ClubOut"];
            /** Played */
            played: number;
            /** Won */
            won: number;
            /** Drawn */
            drawn: number;
            /** Lost */
            lost: number;
            /** Goals For */
            goals_for: number;
            /** Goals Against */
            goals_against: number;
            /** Goal Difference */
            goal_difference: number;
            /** Points */
            points: number;
            /** Form */
            form: string[];
            /**
             * Modelled
             * @default false
             */
            modelled: boolean;
            /** Note */
            note: string | null;
        };
        /** TimelineMarker */
        TimelineMarker: {
            /** Label */
            label: string;
            /**
             * Date
             * Format: date-time
             */
            date: string;
            /** Percent */
            percent: number;
            /**
             * Is Now
             * @default false
             */
            is_now: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    sign_in_api_session_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    sign_out_api_session_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_api_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    clubs_api_clubs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClubOut"][];
                };
            };
        };
    };
    table_api_table_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TableOut"];
                };
            };
        };
    };
    fixtures_api_fixtures_get: {
        parameters: {
            query?: {
                from?: string | null;
                to?: string | null;
                gameweek?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FixtureListOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    fixture_api_fixtures__fixture_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                fixture_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FixtureOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    season_api_season_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeasonOut"];
                };
            };
        };
    };
    home_api_home_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HomeOut"];
                };
            };
        };
    };
    projected_api_table_projected_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectedTableOut"];
                };
            };
        };
    };
    list_predictions_api_predictions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PredictionsOut"];
                };
            };
        };
    };
    put_prediction_api_predictions_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PredictionIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PredictionOut"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    preview_api_predictions_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PreviewIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreviewOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    standings_api_fpl_standings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FplStandingsOut"];
                };
            };
        };
    };
    stream_api_stream_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    status_api_admin_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminStatusOut"];
                };
            };
        };
    };
    listings_api_admin_broadcasters_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BroadcasterOut"][];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    readyz_readyz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
