/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign In
         * @description One field, one code word, compared constant-time.
         */
        post: operations["sign_in_api_session_post"];
        /** Sign Out */
        delete: operations["sign_out_api_session_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clubs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Clubs
         * @description The canonical club table, so the frontend never guesses a crest colour.
         */
        get: operations["clubs_api_clubs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/table": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Table */
        get: operations["table_api_table_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fixtures": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fixtures */
        get: operations["fixtures_api_fixtures_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fixtures/{fixture_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fixture */
        get: operations["fixture_api_fixtures__fixture_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fixtures/{fixture_id}/lineups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fixture Lineups
         * @description On demand only -- opening a match is the one action allowed to reach an upstream.
         */
        get: operations["fixture_lineups_api_fixtures__fixture_id__lineups_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/odds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Odds Round
         * @description The whole current round, bet365 only, with each fixture's drift.
         */
        get: operations["odds_round_api_odds_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/season": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Season */
        get: operations["season_api_season_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/home": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Home
         * @description Everything the front page needs, in one request.
         */
        get: operations["home_api_home_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/table/projected": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Projected
         * @description Current points plus every remaining fixture resolved to last season.
         */
        get: operations["projected_api_table_projected_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/predictions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Predictions */
        get: operations["list_predictions_api_predictions_get"];
        /**
         * Put Prediction
         * @description Owner only, and only before the lock.
         */
        put: operations["put_prediction_api_predictions_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/predictions/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Preview
         * @description Score a draft table against a finished season.
         *
         *     The picker calls this rather than reimplementing the rules in TypeScript --
         *     two implementations of the scoring rules is a bug waiting to happen.
         */
        post: operations["preview_api_predictions_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/leaderboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Leaderboard */
        get: operations["leaderboard_api_leaderboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/h2h": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Head To Head
         * @description Where two people agree, and where they disagree most.
         *
         *     Needs no results, so it works from the moment both have filed -- which is
         *     the whole of the season's opening night.
         */
        get: operations["head_to_head_api_h2h_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fpl/standings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Standings */
        get: operations["standings_api_fpl_standings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fpl/squads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Squads
         * @description Every squad, live, from the moment teams are picked.
         *
         *     FPL exposes picks as soon as the deadline passes -- long before the round is
         *     "scored" -- so there is no reason to withhold them. Points simply read zero
         *     until players take the pitch, which is the honest state rather than a
         *     withheld one.
         */
        get: operations["squads_api_fpl_squads_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/watch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stats */
        get: operations["stats_api_watch_get"];
        put?: never;
        /**
         * Toggle
         * @description Mark a match watched, or un-mark it. Window checked server-side.
         */
        post: operations["toggle_api_watch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/news": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** News */
        get: operations["news_api_news_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat/quotes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Quotes */
        get: operations["quotes_api_chat_quotes_get"];
        put?: never;
        /** Add Quote */
        post: operations["add_quote_api_chat_quotes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat/poll": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Poll */
        get: operations["poll_api_chat_poll_get"];
        put?: never;
        /** Vote */
        post: operations["vote_api_chat_poll_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat/bets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Bets */
        get: operations["bets_api_chat_bets_get"];
        /** Settle Bet */
        put: operations["settle_bet_api_chat_bets_put"];
        /** Propose Bet */
        post: operations["propose_bet_api_chat_bets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Timeline
         * @description Every vote, quote, bet and prediction in one feed, newest first.
         */
        get: operations["timeline_api_timeline_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats/players": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Players */
        get: operations["players_api_stats_players_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats/teams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Teams */
        get: operations["teams_api_stats_teams_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream
         * @description Subscribe to live score, FPL and odds changes for as long as the tab is open.
         */
        get: operations["stream_api_stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Status */
        get: operations["status_api_admin_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/broadcasters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listings */
        get: operations["listings_api_admin_broadcasters_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/calendar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Calendar */
        get: operations["calendar_api_calendar_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Healthz
         * @description Liveness: the process is up. Never touches a dependency.
         */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readyz
         * @description Readiness: the cache answers and the fixture list has been filled.
         */
        get: operations["readyz_readyz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AdminStatusOut */
        AdminStatusOut: {
            /** Caches */
            caches: components["schemas"]["CacheAge"][];
            /** Quotas */
            quotas: components["schemas"]["QuotaOut"][];
            /** Cron */
            cron: components["schemas"]["CronRunOut"][];
            /** Missing Keys */
            missing_keys: string[];
            /** Environment */
            environment: string;
        };
        /** AwardPicks */
        "AwardPicks-Input": {
            /**
             * Golden Boot
             * @default
             */
            golden_boot: string;
            /**
             * Golden Glove
             * @default
             */
            golden_glove: string;
            /**
             * Defender
             * @default
             */
            defender: string;
            /**
             * Playmaker
             * @default
             */
            playmaker: string;
            /**
             * Player Of The Season
             * @default
             */
            player_of_the_season: string;
        };
        /** AwardPicks */
        "AwardPicks-Output": {
            /**
             * Golden Boot
             * @default
             */
            golden_boot: string;
            /**
             * Golden Glove
             * @default
             */
            golden_glove: string;
            /**
             * Defender
             * @default
             */
            defender: string;
            /**
             * Playmaker
             * @default
             */
            playmaker: string;
            /**
             * Player Of The Season
             * @default
             */
            player_of_the_season: string;
        };
        /** BetIn */
        BetIn: {
            /** Opponent */
            opponent: string;
            /** Terms */
            terms: string;
        };
        /** BetOut */
        BetOut: {
            /** Id */
            id: number;
            /** Proposer */
            proposer: string;
            /** Opponent */
            opponent: string;
            /** Terms */
            terms: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Settled At */
            settled_at: string | null;
            /** Winner */
            winner: string | null;
            /**
             * Settled
             * @default false
             */
            settled: boolean;
        };
        /** BetsOut */
        BetsOut: {
            /** Bets */
            bets: components["schemas"]["BetOut"][];
            /** Scoreboard */
            scoreboard: {
                [key: string]: number;
            };
            /** Empty Message */
            empty_message: string | null;
        };
        /** BroadcasterOut */
        BroadcasterOut: {
            /** Country */
            country: string;
            /** Competition */
            competition: string;
            /** Provider */
            provider: string;
            /**
             * Url
             * @default
             */
            url: string;
            /**
             * Verified On
             * @default
             */
            verified_on: string;
            /**
             * Note
             * @default
             */
            note: string;
        };
        /** CacheAge */
        CacheAge: {
            /** Name */
            name: string;
            /** Source */
            source: string;
            /** Age Seconds */
            age_seconds: number;
            /** Stale */
            stale: boolean;
        };
        /** CalendarEventOut */
        CalendarEventOut: {
            /** Title */
            title: string;
            /**
             * Category
             * @enum {string}
             */
            category: "f1" | "boxing" | "ufc" | "other";
            /**
             * Starts At
             * Format: date-time
             */
            starts_at: string;
            /**
             * Note
             * @default
             */
            note: string;
            /** Local Times */
            local_times: components["schemas"]["LocalTimeOut"][];
        };
        /** CalendarOut */
        CalendarOut: {
            /** Events */
            events: components["schemas"]["CalendarEventOut"][];
            /** Empty Message */
            empty_message: string | null;
        };
        /** ChampionsLeaguePicks */
        "ChampionsLeaguePicks-Input": {
            /**
             * Winner
             * @default
             */
            winner: string;
            /**
             * Finalist A
             * @default
             */
            finalist_a: string;
            /**
             * Finalist B
             * @default
             */
            finalist_b: string;
            /**
             * Top Scorer
             * @default
             */
            top_scorer: string;
            /**
             * Draft
             * @default false
             */
            draft: boolean;
        };
        /** ChampionsLeaguePicks */
        "ChampionsLeaguePicks-Output": {
            /**
             * Winner
             * @default
             */
            winner: string;
            /**
             * Finalist A
             * @default
             */
            finalist_a: string;
            /**
             * Finalist B
             * @default
             */
            finalist_b: string;
            /**
             * Top Scorer
             * @default
             */
            top_scorer: string;
            /**
             * Draft
             * @default false
             */
            draft: boolean;
        };
        /**
         * ClubOut
         * @description A club, with everything a crest needs and nothing it does not.
         */
        ClubOut: {
            /** Short Name */
            short_name: string;
            /** Name */
            name: string;
            /** Full Name */
            full_name: string;
            /** Primary */
            primary: string;
            /** On Primary */
            on_primary: string;
            /** Fpl Id */
            fpl_id: number;
        };
        /**
         * CronRunOut
         * @description One scheduler run, as shown in the admin cron log.
         */
        CronRunOut: {
            /** Job */
            job: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Finished At */
            finished_at: string | null;
            /**
             * Ok
             * @default true
             */
            ok: boolean;
            /**
             * Detail
             * @default
             */
            detail: string;
        };
        /** ErrorOut */
        ErrorOut: {
            /** Detail */
            detail: string;
        };
        /** FixtureListOut */
        FixtureListOut: {
            /** Fixtures */
            fixtures: components["schemas"]["FixtureOut"][];
            freshness: components["schemas"]["Freshness"];
            /** Empty Message */
            empty_message: string | null;
        };
        /** FixtureOddsOut */
        FixtureOddsOut: {
            /** Fixture Id */
            fixture_id: number;
            home: components["schemas"]["ClubOut"];
            away: components["schemas"]["ClubOut"];
            odds: components["schemas"]["OddsPrice"];
        };
        /** FixtureOut */
        FixtureOut: {
            /** Id */
            id: number;
            /** Gameweek */
            gameweek: number;
            /** Kickoff */
            kickoff: string | null;
            home: components["schemas"]["ClubOut"];
            away: components["schemas"]["ClubOut"];
            /** Home Score */
            home_score: number | null;
            /** Away Score */
            away_score: number | null;
            /**
             * Started
             * @default false
             */
            started: boolean;
            /**
             * Finished
             * @default false
             */
            finished: boolean;
            /**
             * Postponed
             * @default false
             */
            postponed: boolean;
            /**
             * Minutes
             * @default 0
             */
            minutes: number;
            /** Local Times */
            local_times: components["schemas"]["LocalTimeOut"][];
            odds: components["schemas"]["OddsPrice"] | null;
            /** Derby */
            derby: string | null;
            /** Watched By */
            watched_by: string[];
            /**
             * Watch Open
             * @default false
             */
            watch_open: boolean;
        };
        /** FplChipOut */
        FplChipOut: {
            /** Code */
            code: string;
            /** Name */
            name: string;
            /** Half */
            half: number;
            /** Played In */
            played_in: number | null;
            /**
             * Played
             * @default false
             */
            played: boolean;
        };
        /**
         * FplPlayerOut
         * @description One player in a squad, with whatever the live feed knows so far.
         */
        FplPlayerOut: {
            /** Element */
            element: number;
            /** Name */
            name: string;
            /** Club */
            club: string;
            /** Position */
            position: string;
            /** Slot */
            slot: number;
            /**
             * Is Captain
             * @default false
             */
            is_captain: boolean;
            /**
             * Is Vice Captain
             * @default false
             */
            is_vice_captain: boolean;
            /**
             * Multiplier
             * @default 1
             */
            multiplier: number;
            /**
             * On Bench
             * @default false
             */
            on_bench: boolean;
            /**
             * Points
             * @default 0
             */
            points: number;
            /**
             * Minutes
             * @default 0
             */
            minutes: number;
            /**
             * Goals
             * @default 0
             */
            goals: number;
            /**
             * Assists
             * @default 0
             */
            assists: number;
            /**
             * Bonus
             * @default 0
             */
            bonus: number;
            /**
             * Played
             * @default false
             */
            played: boolean;
            /**
             * Differential
             * @default false
             */
            differential: boolean;
        };
        /** FplSquadOut */
        FplSquadOut: {
            /** Person */
            person: string | null;
            /** Entry Id */
            entry_id: number;
            /** Entry Name */
            entry_name: string;
            /** Starting */
            starting: components["schemas"]["FplPlayerOut"][];
            /** Bench */
            bench: components["schemas"]["FplPlayerOut"][];
            captain: components["schemas"]["FplPlayerOut"] | null;
            vice_captain: components["schemas"]["FplPlayerOut"] | null;
            /** Chip */
            chip: string | null;
            /**
             * Live Points
             * @default 0
             */
            live_points: number;
            /**
             * Bench Points
             * @default 0
             */
            bench_points: number;
            /**
             * Bench Counts
             * @default false
             */
            bench_counts: boolean;
            /** Chips */
            chips: components["schemas"]["FplChipOut"][];
            /**
             * Players Played
             * @default 0
             */
            players_played: number;
            /**
             * Players To Play
             * @default 0
             */
            players_to_play: number;
        };
        /** FplSquadsOut */
        FplSquadsOut: {
            /** Gameweek */
            gameweek: number;
            /** Squads */
            squads: components["schemas"]["FplSquadOut"][];
            /** Captains */
            captains: {
                [key: string]: string;
            };
            freshness: components["schemas"]["Freshness"];
            /** Empty Message */
            empty_message: string | null;
            /** Note */
            note: string | null;
        };
        /** FplStandingRow */
        FplStandingRow: {
            /** Entry Id */
            entry_id: number;
            /** Entry Name */
            entry_name: string;
            /** Player Name */
            player_name: string;
            /** Person */
            person: string | null;
            /** Rank */
            rank: number | null;
            /**
             * Total
             * @default 0
             */
            total: number;
            /**
             * Event Total
             * @default 0
             */
            event_total: number;
            /**
             * Pending
             * @default false
             */
            pending: boolean;
        };
        /** FplStandingsOut */
        FplStandingsOut: {
            /** League Id */
            league_id: number;
            /** League Name */
            league_name: string;
            /** Rows */
            rows: components["schemas"]["FplStandingRow"][];
            /** Gameweek */
            gameweek: number;
            freshness: components["schemas"]["Freshness"];
            /** Empty Message */
            empty_message: string | null;
            /** Unmapped */
            unmapped: number[];
        };
        /**
         * Freshness
         * @description How old a cached payload is, so a panel can say so rather than lie.
         */
        Freshness: {
            /** Source */
            source: string;
            /** Age Seconds */
            age_seconds: number;
            /** Stale */
            stale: boolean;
            /**
             * Available
             * @default true
             */
            available: boolean;
            /** Reason */
            reason: string | null;
        };
        /**
         * H2HAgreement
         * @description A club both people placed in the same position.
         */
        H2HAgreement: {
            club: components["schemas"]["ClubOut"];
            /** Position */
            position: number;
        };
        /**
         * H2HGap
         * @description A club the two people placed furthest apart.
         */
        H2HGap: {
            club: components["schemas"]["ClubOut"];
            /** A Position */
            a_position: number;
            /** B Position */
            b_position: number;
            /** Distance */
            distance: number;
        };
        /**
         * H2HOut
         * @description Where two people agree, and where they disagree most.
         */
        H2HOut: {
            a: components["schemas"]["PersonOut"];
            b: components["schemas"]["PersonOut"];
            /** Agreements */
            agreements: components["schemas"]["H2HAgreement"][];
            /** Gaps */
            gaps: components["schemas"]["H2HGap"][];
            /**
             * Agreement Count
             * @default 0
             */
            agreement_count: number;
            /** Empty Message */
            empty_message: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HomeOut */
        HomeOut: {
            next_match: components["schemas"]["NextMatchOut"];
            season: components["schemas"]["SeasonOut"];
            /** Line Of The Day */
            line_of_the_day: string | null;
        };
        /** LeaderboardOut */
        LeaderboardOut: {
            /** Rows */
            rows: components["schemas"]["LeaderboardRowOut"][];
            /** Leader */
            leader: string | null;
            /** Flop Of The Week */
            flop_of_the_week: string | null;
            /** If Season Ended Today */
            if_season_ended_today: string | null;
            freshness: components["schemas"]["Freshness"];
            /** Empty Message */
            empty_message: string | null;
        };
        /** LeaderboardRowOut */
        LeaderboardRowOut: {
            /** Rank */
            rank: number;
            person: components["schemas"]["PersonOut"];
            /** Total */
            total: number;
            /** Table Points */
            table_points: number;
            /** Award Points */
            award_points: number;
            /** Exact Hits */
            exact_hits: number;
            /** Filed */
            filed: boolean;
            /** Status */
            status: string;
            /**
             * Movement
             * @default 0
             */
            movement: number;
            /** Cursed Pick */
            cursed_pick: string | null;
            /** Form */
            form: number[];
        };
        /** LineupPlayerOut */
        LineupPlayerOut: {
            /** Name */
            name: string;
            /** Number */
            number: number | null;
            /**
             * Position
             * @default
             */
            position: string;
        };
        /** LineupSideOut */
        LineupSideOut: {
            /**
             * Formation
             * @default
             */
            formation: string;
            /** Starting */
            starting: components["schemas"]["LineupPlayerOut"][];
            /** Bench */
            bench: components["schemas"]["LineupPlayerOut"][];
        };
        /** LineupsOut */
        LineupsOut: {
            /** Available */
            available: boolean;
            /** Reason */
            reason: string | null;
            home: components["schemas"]["LineupSideOut"] | null;
            away: components["schemas"]["LineupSideOut"] | null;
        };
        /**
         * LocalTimeOut
         * @description One kickoff rendered for one city.
         */
        LocalTimeOut: {
            /** Place */
            place: string;
            /** Person */
            person: string;
            /** City */
            city: string;
            /** Timezone */
            timezone: string;
            /**
             * Iso
             * Format: date-time
             */
            iso: string;
            /** Time */
            time: string;
            /** Weekday */
            weekday: string;
            /** Day */
            day: string;
            /** Offset */
            offset: string;
            /** Abbreviation */
            abbreviation: string;
            /** Is Night */
            is_night: boolean;
            /** Day Shift */
            day_shift: number;
            /** Broadcaster */
            broadcaster: string | null;
            /** Broadcaster Url */
            broadcaster_url: string | null;
            /** Verified On */
            verified_on: string | null;
        };
        /** LoginIn */
        LoginIn: {
            /** Code */
            code: string;
        };
        /** MeOut */
        MeOut: {
            person: components["schemas"]["PersonOut"];
            /** People */
            people: components["schemas"]["PersonOut"][];
            /** Season */
            season: string;
            /**
             * Prediction Lock
             * Format: date-time
             */
            prediction_lock: string;
            /** Locked */
            locked: boolean;
            /**
             * Server Time
             * Format: date-time
             */
            server_time: string;
        };
        /** NewsItemOut */
        NewsItemOut: {
            /** Title */
            title: string;
            /** Url */
            url: string;
            /** Source */
            source: string;
            /** Published */
            published: string | null;
            /**
             * Summary
             * @default
             */
            summary: string;
            /** Image */
            image: string | null;
        };
        /** NewsOut */
        NewsOut: {
            /** Sky */
            sky: components["schemas"]["NewsItemOut"][];
            /** Sources */
            sources: string[];
            /** Youtube */
            youtube: components["schemas"]["NewsItemOut"][];
            /** Athletic */
            athletic: components["schemas"]["NewsItemOut"][];
            freshness: components["schemas"]["Freshness"];
            /** Empty Message */
            empty_message: string | null;
            /** Youtube Message */
            youtube_message: string | null;
            /** Athletic Message */
            athletic_message: string | null;
        };
        /** NextMatchOut */
        NextMatchOut: {
            fixture: components["schemas"]["FixtureOut"] | null;
            /** Countdown Seconds */
            countdown_seconds: number | null;
            /**
             * In Play
             * @default false
             */
            in_play: boolean;
            /** Message */
            message: string | null;
        };
        /** OddsPrice */
        OddsPrice: {
            /** Home */
            home: number | null;
            /** Draw */
            draw: number | null;
            /** Away */
            away: number | null;
            /**
             * Bookmaker
             * @default bet365
             */
            bookmaker: string;
            /** Captured At */
            captured_at: string | null;
            /** Drift */
            drift: {
                [key: string]: number;
            } | null;
            /**
             * Available
             * @default true
             */
            available: boolean;
            /** Reason */
            reason: string | null;
        };
        /** OddsRoundOut */
        OddsRoundOut: {
            /** Fixtures */
            fixtures: components["schemas"]["FixtureOddsOut"][];
            freshness: components["schemas"]["Freshness"];
            /** Empty Message */
            empty_message: string | null;
        };
        /** PersonOut */
        PersonOut: {
            /** Key */
            key: string;
            /** Name */
            name: string;
            /** City */
            city: string;
            /** Timezone */
            timezone: string;
            /** Country */
            country: string;
            /** Fpl Entry Id */
            fpl_entry_id: number | null;
        };
        /**
         * PlayerStatOut
         * @description One player's season to date, as the stats table shows them.
         */
        PlayerStatOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Full Name */
            full_name: string;
            /** Club */
            club: string;
            /** Club Name */
            club_name: string;
            /** Position */
            position: string;
            /** Minutes */
            minutes: number;
            /** Starts */
            starts: number;
            /** Goals */
            goals: number;
            /** Assists */
            assists: number;
            /** Goal Involvements */
            goal_involvements: number;
            /** Clean Sheets */
            clean_sheets: number;
            /** Saves */
            saves: number;
            /** Yellow Cards */
            yellow_cards: number;
            /** Red Cards */
            red_cards: number;
            /** Bonus */
            bonus: number;
            /** Xg */
            xg: number;
            /** Xa */
            xa: number;
            /** Xgi */
            xgi: number;
            /** Goals Minus Xg */
            goals_minus_xg: number;
            /** Per 90 Goals */
            per_90_goals: number;
            /** Per 90 Assists */
            per_90_assists: number;
            /** Ict */
            ict: number;
            /** Form */
            form: number;
            /** Points */
            points: number;
            /** Points Per Game */
            points_per_game: number;
            /** Price */
            price: number;
            /** Selected By */
            selected_by: number;
            /**
             * Status
             * @default a
             */
            status: string;
            /**
             * News
             * @default
             */
            news: string;
        };
        /** PlayerStatsOut */
        PlayerStatsOut: {
            /** Players */
            players: components["schemas"]["PlayerStatOut"][];
            /**
             * Gameweek
             * @default 0
             */
            gameweek: number;
            /**
             * Matches Played
             * @default 0
             */
            matches_played: number;
            freshness: components["schemas"]["Freshness"];
            /** Empty Message */
            empty_message: string | null;
        };
        /** PollOptionOut */
        PollOptionOut: {
            /** Choice */
            choice: string;
            /** Votes */
            votes: number;
            /** Voters */
            voters: string[];
        };
        /** PollOut */
        PollOut: {
            /** Id */
            id: number;
            /** Question */
            question: string;
            /** Options */
            options: components["schemas"]["PollOptionOut"][];
            /**
             * Opens At
             * Format: date-time
             */
            opens_at: string;
            /**
             * Closes At
             * Format: date-time
             */
            closes_at: string;
            /** Open */
            open: boolean;
            /** My Vote */
            my_vote: string | null;
            /**
             * Total Votes
             * @default 0
             */
            total_votes: number;
        };
        /** PollsOut */
        PollsOut: {
            current: components["schemas"]["PollOut"] | null;
            /** Archive */
            archive: components["schemas"]["PollOut"][];
            /** Empty Message */
            empty_message: string | null;
        };
        /** PredictionIn */
        PredictionIn: {
            /** Table */
            table?: string[];
            awards?: components["schemas"]["AwardPicks-Input"];
            champions_league?: components["schemas"]["ChampionsLeaguePicks-Input"];
        };
        /** PredictionOut */
        PredictionOut: {
            /** Person */
            person: string;
            /** Filed */
            filed: boolean;
            /**
             * Redacted
             * @default false
             */
            redacted: boolean;
            /** Table */
            table: string[];
            awards: components["schemas"]["AwardPicks-Output"] | null;
            champions_league: components["schemas"]["ChampionsLeaguePicks-Output"] | null;
            /** Submitted At */
            submitted_at: string | null;
            /**
             * Locked
             * @default false
             */
            locked: boolean;
            /**
             * Status
             * @default open
             * @enum {string}
             */
            status: "filed" | "open" | "did-not-file";
        };
        /** PredictionsOut */
        PredictionsOut: {
            /** Predictions */
            predictions: components["schemas"]["PredictionOut"][];
            /** Locked */
            locked: boolean;
            /**
             * Lock At
             * Format: date-time
             */
            lock_at: string;
            /** Seconds Remaining */
            seconds_remaining: number;
        };
        /** PreviewIn */
        PreviewIn: {
            /** Table */
            table: string[];
            awards?: components["schemas"]["AwardPicks-Input"] | null;
            /**
             * Against Season
             * @default 2025-26
             */
            against_season: string;
        };
        /** PreviewOut */
        PreviewOut: {
            /** Total */
            total: number;
            /** Table Points */
            table_points: number;
            /** Award Points */
            award_points: number;
            /** Exact Hits */
            exact_hits: number;
            /** Near Hits */
            near_hits: number;
            /** Top Four Bonus */
            top_four_bonus: number;
            /** Champion Bonus */
            champion_bonus: number;
            /** Against Season */
            against_season: string;
            /** Per Club */
            per_club: {
                [key: string]: unknown;
            }[];
        };
        /** ProjectedTableOut */
        ProjectedTableOut: {
            /** Rows */
            rows: components["schemas"]["TableRowOut"][];
            /** Gameweek */
            gameweek: number;
            /** Matches Played */
            matches_played: number;
            /** Season Started */
            season_started: boolean;
            freshness: components["schemas"]["Freshness"];
            /** Empty Message */
            empty_message: string | null;
            /** Modelled Rows */
            modelled_rows: string[];
            /**
             * Method
             * @default
             */
            method: string;
        };
        /** QuotaOut */
        QuotaOut: {
            /** Source */
            source: string;
            /** Used */
            used: number;
            /** Budget */
            budget: number;
            /** Remaining */
            remaining: number;
            /** Window */
            window: string;
            /**
             * Note
             * @default
             */
            note: string;
        };
        /** QuoteIn */
        QuoteIn: {
            /** Body */
            body: string;
            /** Subject Type */
            subject_type?: ("club" | "player" | "match") | null;
            /** Subject Id */
            subject_id?: string | null;
        };
        /** QuoteOut */
        QuoteOut: {
            /** Id */
            id: number;
            /** Person */
            person: string;
            /** Body */
            body: string;
            /** Subject Type */
            subject_type: string | null;
            /** Subject Id */
            subject_id: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * SeasonOut
         * @description Computed from fixture data and the current date, never hardcoded.
         */
        SeasonOut: {
            /**
             * Starts
             * Format: date-time
             */
            starts: string;
            /**
             * Ends
             * Format: date-time
             */
            ends: string;
            /**
             * Today
             * Format: date-time
             */
            today: string;
            /** Percent */
            percent: number;
            /** Day */
            day: number;
            /** Total Days */
            total_days: number;
            /** Days Remaining */
            days_remaining: number;
            /** Gameweeks Played */
            gameweeks_played: number;
            /** Gameweeks Total */
            gameweeks_total: number;
            /** Matches Played */
            matches_played: number;
            /** Matches Total */
            matches_total: number;
            /** Matches Remaining */
            matches_remaining: number;
            /** Watched */
            watched: number;
            /** Markers */
            markers: components["schemas"]["TimelineMarker"][];
        };
        /** SettleBetIn */
        SettleBetIn: {
            /** Bet Id */
            bet_id: number;
            /** Winner */
            winner: string;
        };
        /** TableOut */
        TableOut: {
            /** Rows */
            rows: components["schemas"]["TableRowOut"][];
            /** Gameweek */
            gameweek: number;
            /** Matches Played */
            matches_played: number;
            /** Season Started */
            season_started: boolean;
            freshness: components["schemas"]["Freshness"];
            /** Empty Message */
            empty_message: string | null;
        };
        /** TableRowOut */
        TableRowOut: {
            /** Position */
            position: number;
            club: components["schemas"]["ClubOut"];
            /** Played */
            played: number;
            /** Won */
            won: number;
            /** Drawn */
            drawn: number;
            /** Lost */
            lost: number;
            /** Goals For */
            goals_for: number;
            /** Goals Against */
            goals_against: number;
            /** Goal Difference */
            goal_difference: number;
            /** Points */
            points: number;
            /** Form */
            form: string[];
            /**
             * Modelled
             * @default false
             */
            modelled: boolean;
            /** Note */
            note: string | null;
        };
        /** TeamStatOut */
        TeamStatOut: {
            club: components["schemas"]["ClubOut"];
            /** Position */
            position: number;
            /** Played */
            played: number;
            /** Won */
            won: number;
            /** Drawn */
            drawn: number;
            /** Lost */
            lost: number;
            /** Goals For */
            goals_for: number;
            /** Goals Against */
            goals_against: number;
            /** Goal Difference */
            goal_difference: number;
            /** Points */
            points: number;
            /** Clean Sheets */
            clean_sheets: number;
            /** Failed To Score */
            failed_to_score: number;
            /** Goals Per Game */
            goals_per_game: number;
            /** Conceded Per Game */
            conceded_per_game: number;
            /** Form */
            form: string[];
            /**
             * Squad Xg
             * @default 0
             */
            squad_xg: number;
            /**
             * Squad Xga
             * @default 0
             */
            squad_xga: number;
        };
        /** TeamStatsOut */
        TeamStatsOut: {
            /** Teams */
            teams: components["schemas"]["TeamStatOut"][];
            /**
             * Matches Played
             * @default 0
             */
            matches_played: number;
            freshness: components["schemas"]["Freshness"];
            /** Empty Message */
            empty_message: string | null;
        };
        /** TimelineEntryOut */
        TimelineEntryOut: {
            /** Kind */
            kind: string;
            /**
             * At
             * Format: date-time
             */
            at: string;
            /** Person */
            person: string | null;
            /** Title */
            title: string;
            /** Detail */
            detail: string | null;
        };
        /** TimelineMarker */
        TimelineMarker: {
            /** Label */
            label: string;
            /**
             * Date
             * Format: date-time
             */
            date: string;
            /** Percent */
            percent: number;
            /**
             * Is Now
             * @default false
             */
            is_now: boolean;
        };
        /** TimelineOut */
        TimelineOut: {
            /** Entries */
            entries: components["schemas"]["TimelineEntryOut"][];
            /** Empty Message */
            empty_message: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VoteIn */
        VoteIn: {
            /** Poll Id */
            poll_id: number;
            /** Choice */
            choice: string;
        };
        /** WatchStatsOut */
        WatchStatsOut: {
            /** Person */
            person: string;
            /** Watched */
            watched: number;
            /** Total Matches */
            total_matches: number;
            /** Percent */
            percent: number;
            /** Hours */
            hours: number;
            /** Night Medals */
            night_medals: number;
            /** Streak */
            streak: number;
            freshness: components["schemas"]["Freshness"];
        };
        /** WatchToggleIn */
        WatchToggleIn: {
            /** Fixture Id */
            fixture_id: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    sign_in_api_session_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    sign_out_api_session_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_api_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    clubs_api_clubs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClubOut"][];
                };
            };
        };
    };
    table_api_table_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TableOut"];
                };
            };
        };
    };
    fixtures_api_fixtures_get: {
        parameters: {
            query?: {
                from?: string | null;
                to?: string | null;
                gameweek?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FixtureListOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    fixture_api_fixtures__fixture_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                fixture_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FixtureOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    fixture_lineups_api_fixtures__fixture_id__lineups_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                fixture_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LineupsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    odds_round_api_odds_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OddsRoundOut"];
                };
            };
        };
    };
    season_api_season_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeasonOut"];
                };
            };
        };
    };
    home_api_home_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HomeOut"];
                };
            };
        };
    };
    projected_api_table_projected_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectedTableOut"];
                };
            };
        };
    };
    list_predictions_api_predictions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PredictionsOut"];
                };
            };
        };
    };
    put_prediction_api_predictions_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PredictionIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PredictionOut"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    preview_api_predictions_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PreviewIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreviewOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    leaderboard_api_leaderboard_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeaderboardOut"];
                };
            };
        };
    };
    head_to_head_api_h2h_get: {
        parameters: {
            query: {
                a: string;
                b: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["H2HOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    standings_api_fpl_standings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FplStandingsOut"];
                };
            };
        };
    };
    squads_api_fpl_squads_get: {
        parameters: {
            query?: {
                gw?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FplSquadsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stats_api_watch_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchStatsOut"];
                };
            };
        };
    };
    toggle_api_watch_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WatchToggleIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchStatsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    news_api_news_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NewsOut"];
                };
            };
        };
    };
    quotes_api_chat_quotes_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuoteOut"][];
                };
            };
        };
    };
    add_quote_api_chat_quotes_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuoteIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuoteOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    poll_api_chat_poll_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PollsOut"];
                };
            };
        };
    };
    vote_api_chat_poll_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VoteIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PollOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bets_api_chat_bets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BetsOut"];
                };
            };
        };
    };
    settle_bet_api_chat_bets_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettleBetIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BetOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    propose_bet_api_chat_bets_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BetIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BetOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    timeline_api_timeline_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimelineOut"];
                };
            };
        };
    };
    players_api_stats_players_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerStatsOut"];
                };
            };
        };
    };
    teams_api_stats_teams_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamStatsOut"];
                };
            };
        };
    };
    stream_api_stream_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    status_api_admin_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminStatusOut"];
                };
            };
        };
    };
    listings_api_admin_broadcasters_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BroadcasterOut"][];
                };
            };
        };
    };
    calendar_api_calendar_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalendarOut"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    readyz_readyz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
